# Generated by Django 3.1.7 on 2021-10-12 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Reflist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='ref_files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'rtf'])], verbose_name='Файл')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refs.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Список работ',
                'verbose_name_plural': 'Список работ',
                'ordering': ['-time_create'],
            },
        ),
    ]
