version: '3.7'

services:
  rf_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  rf_bot:
    build: .
    command: python /usr/src/mysite/manage.py bot
    volumes:
      - .:/usr/src/mysite
    depends_on:
      - rf_db

  rf_web:
    build: .
    command: python /usr/src/mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/mysite
    ports:
      - 8000:8000
    env_file:
      - ./.env

    depends_on:
      - rf_db
volumes:
  postgres_data:
